---
- name: Set rtorrent_configured variable to false.
  ansible.builtin.set_fact:
    rtorrent_configured: false

- name: Debug rtorrent_configured variable.
  ansible.builtin.debug:
    var: rtorrent_configured
  tags:
    - never
    - debug