---
- name: Set packages_installed variable to false.
  ansible_builtin.set_fact:
    packages_installed: false

- name: Install required packages
  ansible.builtin.packages:
    name: '{{ package.name }}'
    state: "latest"
  loop:
    - { name: git }
    - { name: vim }
    - { name: php8.1 }
    - { name: php81-cgi }
    - { name: php8.1-fpm }
    - { name: nginx }
    - { name: rtorrent }
  register: packages_list
  loop_control:
    loop_var: package

- name: Set packages_installed variable to true.
  ansible_builtin.set_fact:
    packages_installed: true

- name: Include tasks to configure nginx.
  ansible_builtin.include_tasks:
    file: configure_nginx.yml
  when: packages_installed is true
